<?php
/**
 * Copyright 2013 Indeed, Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
$tlds = array();

$rawTlds = file("http://mxr.mozilla.org/mozilla-central/source/netwerk/dns/effective_tld_names.dat?raw=1");

foreach ($rawTlds as $tld) {
	$tld = trim($tld);
	$pos = strpos($tld, "//");
	if (!empty($tld) && $pos === false){
		tldHelper(trim($tld), $tlds);
	}
}

$tldSuffix = var_export($tlds, true);

echo <<<EOT
<?
/**
 * Generated by updateEffectiveTLDs.php
 * See https://github.com/Hillgod/effective-TLDs for
 * project and license information.
 */
class TldSuffix {
	public static \$tldSuffixes = $tldSuffix;
}
EOT;

function tldHelper($tld, array &$tlds) {
	$dotLoc = strrpos($tld, '.');

	if ($dotLoc !== false) {
		$tmp = $tld;
		$tld = substr($tmp, $dotLoc + 1);
		$rest = substr($tmp, 0, $dotLoc);

		if (!array_key_exists($tld, $tlds)) {
			$tlds[$tld] = array('#' => false);

		}
		tldHelper($rest, $tlds[$tld]);
	} else {
		if (substr($tld, 1, 1) == '!') {
			// exception case
			$tlds[$tld] = '!';
		} elseif (!array_key_exists($tld, $tlds)) {
			$tlds[$tld] = array('#' => true);
		} else {
			$tlds[$tld]['#'] = true;
		}
	}
}